/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaDto } from './PaginationMetaDto';
import {
    PaginationMetaDtoFromJSON,
    PaginationMetaDtoFromJSONTyped,
    PaginationMetaDtoToJSON,
    PaginationMetaDtoToJSONTyped,
} from './PaginationMetaDto';
import type { AdminUserDto } from './AdminUserDto';
import {
    AdminUserDtoFromJSON,
    AdminUserDtoFromJSONTyped,
    AdminUserDtoToJSON,
    AdminUserDtoToJSONTyped,
} from './AdminUserDto';

/**
 * 
 * @export
 * @interface AdminUsersPageDto
 */
export interface AdminUsersPageDto {
    /**
     * 
     * @type {Array<AdminUserDto>}
     * @memberof AdminUsersPageDto
     */
    items: Array<AdminUserDto>;
    /**
     * 
     * @type {PaginationMetaDto}
     * @memberof AdminUsersPageDto
     */
    meta: PaginationMetaDto;
}

/**
 * Check if a given object implements the AdminUsersPageDto interface.
 */
export function instanceOfAdminUsersPageDto(value: object): value is AdminUsersPageDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function AdminUsersPageDtoFromJSON(json: any): AdminUsersPageDto {
    return AdminUsersPageDtoFromJSONTyped(json, false);
}

export function AdminUsersPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUsersPageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminUserDtoFromJSON)),
        'meta': PaginationMetaDtoFromJSON(json['meta']),
    };
}

export function AdminUsersPageDtoToJSON(json: any): AdminUsersPageDto {
    return AdminUsersPageDtoToJSONTyped(json, false);
}

export function AdminUsersPageDtoToJSONTyped(value?: AdminUsersPageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminUserDtoToJSON)),
        'meta': PaginationMetaDtoToJSON(value['meta']),
    };
}

