/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtistRequestDto } from './ArtistRequestDto';
import {
    ArtistRequestDtoFromJSON,
    ArtistRequestDtoFromJSONTyped,
    ArtistRequestDtoToJSON,
    ArtistRequestDtoToJSONTyped,
} from './ArtistRequestDto';
import type { PaginationMetaDto } from './PaginationMetaDto';
import {
    PaginationMetaDtoFromJSON,
    PaginationMetaDtoFromJSONTyped,
    PaginationMetaDtoToJSON,
    PaginationMetaDtoToJSONTyped,
} from './PaginationMetaDto';

/**
 * 
 * @export
 * @interface ArtistRequestPageDto
 */
export interface ArtistRequestPageDto {
    /**
     * 
     * @type {Array<ArtistRequestDto>}
     * @memberof ArtistRequestPageDto
     */
    items: Array<ArtistRequestDto>;
    /**
     * 
     * @type {PaginationMetaDto}
     * @memberof ArtistRequestPageDto
     */
    meta: PaginationMetaDto;
}

/**
 * Check if a given object implements the ArtistRequestPageDto interface.
 */
export function instanceOfArtistRequestPageDto(value: object): value is ArtistRequestPageDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ArtistRequestPageDtoFromJSON(json: any): ArtistRequestPageDto {
    return ArtistRequestPageDtoFromJSONTyped(json, false);
}

export function ArtistRequestPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistRequestPageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ArtistRequestDtoFromJSON)),
        'meta': PaginationMetaDtoFromJSON(json['meta']),
    };
}

export function ArtistRequestPageDtoToJSON(json: any): ArtistRequestPageDto {
    return ArtistRequestPageDtoToJSONTyped(json, false);
}

export function ArtistRequestPageDtoToJSONTyped(value?: ArtistRequestPageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ArtistRequestDtoToJSON)),
        'meta': PaginationMetaDtoToJSON(value['meta']),
    };
}

