/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistRequestDto
 */
export interface ArtistRequestDto {
    /**
     * As most recently typed, not the grouping key
     * @type {string}
     * @memberof ArtistRequestDto
     */
    name: string;
    /**
     * How many people have asked for it
     * @type {number}
     * @memberof ArtistRequestDto
     */
    count: number;
    /**
     * 
     * @type {Date}
     * @memberof ArtistRequestDto
     */
    lastAskedAt: Date;
}

/**
 * Check if a given object implements the ArtistRequestDto interface.
 */
export function instanceOfArtistRequestDto(value: object): value is ArtistRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('lastAskedAt' in value) || value['lastAskedAt'] === undefined) return false;
    return true;
}

export function ArtistRequestDtoFromJSON(json: any): ArtistRequestDto {
    return ArtistRequestDtoFromJSONTyped(json, false);
}

export function ArtistRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
        'lastAskedAt': (new Date(json['lastAskedAt'])),
    };
}

export function ArtistRequestDtoToJSON(json: any): ArtistRequestDto {
    return ArtistRequestDtoToJSONTyped(json, false);
}

export function ArtistRequestDtoToJSONTyped(value?: ArtistRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'count': value['count'],
        'lastAskedAt': value['lastAskedAt'].toISOString(),
    };
}

