/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeedbackControllerDto
 */
export interface CreateFeedbackControllerDto {
    /**
     * 
     * @type {string}
     * @memberof CreateFeedbackControllerDto
     */
    kind: CreateFeedbackControllerDtoKindEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateFeedbackControllerDto
     */
    message: string;
    /**
     * Where to reply, if anywhere
     * @type {string}
     * @memberof CreateFeedbackControllerDto
     */
    email?: string;
    /**
     * The page the report was sent from
     * @type {string}
     * @memberof CreateFeedbackControllerDto
     */
    pagePath?: string;
    /**
     * The app release the report was sent from
     * @type {string}
     * @memberof CreateFeedbackControllerDto
     */
    appVersion?: string;
    /**
     * Left empty by people; a filled one is dropped silently
     * @type {string}
     * @memberof CreateFeedbackControllerDto
     */
    website?: string;
}


/**
 * @export
 */
export const CreateFeedbackControllerDtoKindEnum = {
    Bug: 'BUG',
    Suggestion: 'SUGGESTION'
} as const;
export type CreateFeedbackControllerDtoKindEnum = typeof CreateFeedbackControllerDtoKindEnum[keyof typeof CreateFeedbackControllerDtoKindEnum];


/**
 * Check if a given object implements the CreateFeedbackControllerDto interface.
 */
export function instanceOfCreateFeedbackControllerDto(value: object): value is CreateFeedbackControllerDto {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateFeedbackControllerDtoFromJSON(json: any): CreateFeedbackControllerDto {
    return CreateFeedbackControllerDtoFromJSONTyped(json, false);
}

export function CreateFeedbackControllerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeedbackControllerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'message': json['message'],
        'email': json['email'] == null ? undefined : json['email'],
        'pagePath': json['pagePath'] == null ? undefined : json['pagePath'],
        'appVersion': json['appVersion'] == null ? undefined : json['appVersion'],
        'website': json['website'] == null ? undefined : json['website'],
    };
}

export function CreateFeedbackControllerDtoToJSON(json: any): CreateFeedbackControllerDto {
    return CreateFeedbackControllerDtoToJSONTyped(json, false);
}

export function CreateFeedbackControllerDtoToJSONTyped(value?: CreateFeedbackControllerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'message': value['message'],
        'email': value['email'],
        'pagePath': value['pagePath'],
        'appVersion': value['appVersion'],
        'website': value['website'],
    };
}

