/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRoomControllerDto
 */
export interface CreateRoomControllerDto {
    /**
     * Number of rounds for the game
     * @type {number}
     * @memberof CreateRoomControllerDto
     */
    roundCount: CreateRoomControllerDtoRoundCountEnum;
    /**
     * Seats in the room
     * @type {number}
     * @memberof CreateRoomControllerDto
     */
    maxPlayers?: CreateRoomControllerDtoMaxPlayersEnum;
    /**
     * Whether the room is listed for anyone to find. Off makes it reachable only by its invite code.
     * @type {boolean}
     * @memberof CreateRoomControllerDto
     */
    findable?: boolean;
}


/**
 * @export
 */
export const CreateRoomControllerDtoRoundCountEnum = {
    NUMBER_3: 3,
    NUMBER_5: 5,
    NUMBER_10: 10
} as const;
export type CreateRoomControllerDtoRoundCountEnum = typeof CreateRoomControllerDtoRoundCountEnum[keyof typeof CreateRoomControllerDtoRoundCountEnum];

/**
 * @export
 */
export const CreateRoomControllerDtoMaxPlayersEnum = {
    NUMBER_5: 5,
    NUMBER_10: 10,
    NUMBER_20: 20,
    NUMBER_50: 50
} as const;
export type CreateRoomControllerDtoMaxPlayersEnum = typeof CreateRoomControllerDtoMaxPlayersEnum[keyof typeof CreateRoomControllerDtoMaxPlayersEnum];


/**
 * Check if a given object implements the CreateRoomControllerDto interface.
 */
export function instanceOfCreateRoomControllerDto(value: object): value is CreateRoomControllerDto {
    if (!('roundCount' in value) || value['roundCount'] === undefined) return false;
    return true;
}

export function CreateRoomControllerDtoFromJSON(json: any): CreateRoomControllerDto {
    return CreateRoomControllerDtoFromJSONTyped(json, false);
}

export function CreateRoomControllerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoomControllerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roundCount': json['roundCount'],
        'maxPlayers': json['maxPlayers'] == null ? undefined : json['maxPlayers'],
        'findable': json['findable'] == null ? undefined : json['findable'],
    };
}

export function CreateRoomControllerDtoToJSON(json: any): CreateRoomControllerDto {
    return CreateRoomControllerDtoToJSONTyped(json, false);
}

export function CreateRoomControllerDtoToJSONTyped(value?: CreateRoomControllerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roundCount': value['roundCount'],
        'maxPlayers': value['maxPlayers'],
        'findable': value['findable'],
    };
}

