/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailChangeResultDto
 */
export interface EmailChangeResultDto {
    /**
     * Whether the link was live. False covers wrong, expired, used and replaced alike.
     * @type {boolean}
     * @memberof EmailChangeResultDto
     */
    done: boolean;
}

/**
 * Check if a given object implements the EmailChangeResultDto interface.
 */
export function instanceOfEmailChangeResultDto(value: object): value is EmailChangeResultDto {
    if (!('done' in value) || value['done'] === undefined) return false;
    return true;
}

export function EmailChangeResultDtoFromJSON(json: any): EmailChangeResultDto {
    return EmailChangeResultDtoFromJSONTyped(json, false);
}

export function EmailChangeResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailChangeResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'done': json['done'],
    };
}

export function EmailChangeResultDtoToJSON(json: any): EmailChangeResultDto {
    return EmailChangeResultDtoToJSONTyped(json, false);
}

export function EmailChangeResultDtoToJSONTyped(value?: EmailChangeResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'done': value['done'],
    };
}

