/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackDto
 */
export interface FeedbackDto {
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    kind: FeedbackDtoKindEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    userDisplayName?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    pagePath?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    appVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    userAgent?: string;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackDto
     */
    resolvedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackDto
     */
    createdAt: Date;
}


/**
 * @export
 */
export const FeedbackDtoKindEnum = {
    Bug: 'BUG',
    Suggestion: 'SUGGESTION',
    ArtistRequest: 'ARTIST_REQUEST'
} as const;
export type FeedbackDtoKindEnum = typeof FeedbackDtoKindEnum[keyof typeof FeedbackDtoKindEnum];


/**
 * Check if a given object implements the FeedbackDto interface.
 */
export function instanceOfFeedbackDto(value: object): value is FeedbackDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function FeedbackDtoFromJSON(json: any): FeedbackDto {
    return FeedbackDtoFromJSONTyped(json, false);
}

export function FeedbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'message': json['message'],
        'email': json['email'] == null ? undefined : json['email'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userDisplayName': json['userDisplayName'] == null ? undefined : json['userDisplayName'],
        'pagePath': json['pagePath'] == null ? undefined : json['pagePath'],
        'appVersion': json['appVersion'] == null ? undefined : json['appVersion'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'resolvedAt': json['resolvedAt'] == null ? undefined : (new Date(json['resolvedAt'])),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function FeedbackDtoToJSON(json: any): FeedbackDto {
    return FeedbackDtoToJSONTyped(json, false);
}

export function FeedbackDtoToJSONTyped(value?: FeedbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'message': value['message'],
        'email': value['email'],
        'userId': value['userId'],
        'userDisplayName': value['userDisplayName'],
        'pagePath': value['pagePath'],
        'appVersion': value['appVersion'],
        'userAgent': value['userAgent'],
        'resolvedAt': value['resolvedAt'] == null ? value['resolvedAt'] : value['resolvedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
    };
}

