/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaDto } from './PaginationMetaDto';
import {
    PaginationMetaDtoFromJSON,
    PaginationMetaDtoFromJSONTyped,
    PaginationMetaDtoToJSON,
    PaginationMetaDtoToJSONTyped,
} from './PaginationMetaDto';
import type { FeedbackDto } from './FeedbackDto';
import {
    FeedbackDtoFromJSON,
    FeedbackDtoFromJSONTyped,
    FeedbackDtoToJSON,
    FeedbackDtoToJSONTyped,
} from './FeedbackDto';

/**
 * 
 * @export
 * @interface FeedbackPageDto
 */
export interface FeedbackPageDto {
    /**
     * 
     * @type {Array<FeedbackDto>}
     * @memberof FeedbackPageDto
     */
    items: Array<FeedbackDto>;
    /**
     * 
     * @type {PaginationMetaDto}
     * @memberof FeedbackPageDto
     */
    meta: PaginationMetaDto;
}

/**
 * Check if a given object implements the FeedbackPageDto interface.
 */
export function instanceOfFeedbackPageDto(value: object): value is FeedbackPageDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function FeedbackPageDtoFromJSON(json: any): FeedbackPageDto {
    return FeedbackPageDtoFromJSONTyped(json, false);
}

export function FeedbackPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackPageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FeedbackDtoFromJSON)),
        'meta': PaginationMetaDtoFromJSON(json['meta']),
    };
}

export function FeedbackPageDtoToJSON(json: any): FeedbackPageDto {
    return FeedbackPageDtoToJSONTyped(json, false);
}

export function FeedbackPageDtoToJSONTyped(value?: FeedbackPageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(FeedbackDtoToJSON)),
        'meta': PaginationMetaDtoToJSON(value['meta']),
    };
}

