/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuessAudioDto
 */
export interface GuessAudioDto {
    /**
     * Whether the snippet was started this round
     * @type {boolean}
     * @memberof GuessAudioDto
     */
    played: boolean;
    /**
     * How the last snippet was played, when one was
     * @type {string}
     * @memberof GuessAudioDto
     */
    path?: GuessAudioDtoPathEnum;
    /**
     * The Web Audio context's state, including WebKit's `interrupted`
     * @type {string}
     * @memberof GuessAudioDto
     */
    contextState?: string;
    /**
     * Whether the silent element holding the iOS playback session is playing
     * @type {boolean}
     * @memberof GuessAudioDto
     */
    sessionHeld: boolean;
    /**
     * 
     * @type {string}
     * @memberof GuessAudioDto
     */
    userAgent?: string;
}


/**
 * @export
 */
export const GuessAudioDtoPathEnum = {
    WebAudio: 'web-audio',
    Element: 'element'
} as const;
export type GuessAudioDtoPathEnum = typeof GuessAudioDtoPathEnum[keyof typeof GuessAudioDtoPathEnum];


/**
 * Check if a given object implements the GuessAudioDto interface.
 */
export function instanceOfGuessAudioDto(value: object): value is GuessAudioDto {
    if (!('played' in value) || value['played'] === undefined) return false;
    if (!('sessionHeld' in value) || value['sessionHeld'] === undefined) return false;
    return true;
}

export function GuessAudioDtoFromJSON(json: any): GuessAudioDto {
    return GuessAudioDtoFromJSONTyped(json, false);
}

export function GuessAudioDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuessAudioDto {
    if (json == null) {
        return json;
    }
    return {
        
        'played': json['played'],
        'path': json['path'] == null ? undefined : json['path'],
        'contextState': json['contextState'] == null ? undefined : json['contextState'],
        'sessionHeld': json['sessionHeld'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function GuessAudioDtoToJSON(json: any): GuessAudioDto {
    return GuessAudioDtoToJSONTyped(json, false);
}

export function GuessAudioDtoToJSONTyped(value?: GuessAudioDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'played': value['played'],
        'path': value['path'],
        'contextState': value['contextState'],
        'sessionHeld': value['sessionHeld'],
        'userAgent': value['userAgent'],
    };
}

