/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportPlaylistControllerDto
 */
export interface ImportPlaylistControllerDto {
    /**
     * 
     * @type {string}
     * @memberof ImportPlaylistControllerDto
     */
    source: ImportPlaylistControllerDtoSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof ImportPlaylistControllerDto
     */
    link: string;
    /**
     * Where the player keeps the playlist, when the link is a copy
     * @type {string}
     * @memberof ImportPlaylistControllerDto
     */
    origin?: ImportPlaylistControllerDtoOriginEnum;
}


/**
 * @export
 */
export const ImportPlaylistControllerDtoSourceEnum = {
    Deezer: 'DEEZER',
    Spotify: 'SPOTIFY',
    AppleMusic: 'APPLE_MUSIC'
} as const;
export type ImportPlaylistControllerDtoSourceEnum = typeof ImportPlaylistControllerDtoSourceEnum[keyof typeof ImportPlaylistControllerDtoSourceEnum];

/**
 * @export
 */
export const ImportPlaylistControllerDtoOriginEnum = {
    Deezer: 'DEEZER',
    Spotify: 'SPOTIFY',
    AppleMusic: 'APPLE_MUSIC'
} as const;
export type ImportPlaylistControllerDtoOriginEnum = typeof ImportPlaylistControllerDtoOriginEnum[keyof typeof ImportPlaylistControllerDtoOriginEnum];


/**
 * Check if a given object implements the ImportPlaylistControllerDto interface.
 */
export function instanceOfImportPlaylistControllerDto(value: object): value is ImportPlaylistControllerDto {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function ImportPlaylistControllerDtoFromJSON(json: any): ImportPlaylistControllerDto {
    return ImportPlaylistControllerDtoFromJSONTyped(json, false);
}

export function ImportPlaylistControllerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportPlaylistControllerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'link': json['link'],
        'origin': json['origin'] == null ? undefined : json['origin'],
    };
}

export function ImportPlaylistControllerDtoToJSON(json: any): ImportPlaylistControllerDto {
    return ImportPlaylistControllerDtoToJSONTyped(json, false);
}

export function ImportPlaylistControllerDtoToJSONTyped(value?: ImportPlaylistControllerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'link': value['link'],
        'origin': value['origin'],
    };
}

