/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportQuotaDto
 */
export interface ImportQuotaDto {
    /**
     * Playlist reads left today
     * @type {number}
     * @memberof ImportQuotaDto
     */
    left: number;
    /**
     * Reads a player gets each day
     * @type {number}
     * @memberof ImportQuotaDto
     */
    limit: number;
    /**
     * Seconds until the count starts over
     * @type {number}
     * @memberof ImportQuotaDto
     */
    resetsIn?: number;
}

/**
 * Check if a given object implements the ImportQuotaDto interface.
 */
export function instanceOfImportQuotaDto(value: object): value is ImportQuotaDto {
    if (!('left' in value) || value['left'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ImportQuotaDtoFromJSON(json: any): ImportQuotaDto {
    return ImportQuotaDtoFromJSONTyped(json, false);
}

export function ImportQuotaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportQuotaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'left': json['left'],
        'limit': json['limit'],
        'resetsIn': json['resetsIn'] == null ? undefined : json['resetsIn'],
    };
}

export function ImportQuotaDtoToJSON(json: any): ImportQuotaDto {
    return ImportQuotaDtoToJSONTyped(json, false);
}

export function ImportQuotaDtoToJSONTyped(value?: ImportQuotaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'left': value['left'],
        'limit': value['limit'],
        'resetsIn': value['resetsIn'],
    };
}

