/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportedSetDto
 */
export interface ImportedSetDto {
    /**
     * Stable id, used to start a round
     * @type {string}
     * @memberof ImportedSetDto
     */
    id: string;
    /**
     * Which axis this groups by
     * @type {string}
     * @memberof ImportedSetDto
     */
    type: ImportedSetDtoTypeEnum;
    /**
     * What the tile is called
     * @type {string}
     * @memberof ImportedSetDto
     */
    name: string;
    /**
     * In the URL, so a shared link survives a rename
     * @type {string}
     * @memberof ImportedSetDto
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof ImportedSetDto
     */
    trackCount: number;
    /**
     * Album art of the best known song in the group, absent if none of them has any
     * @type {string}
     * @memberof ImportedSetDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportedSetDto
     */
    source: ImportedSetDtoSourceEnum;
    /**
     * The playlist on its own service
     * @type {string}
     * @memberof ImportedSetDto
     */
    externalUrl: string;
    /**
     * Its songs have not been read yet
     * @type {boolean}
     * @memberof ImportedSetDto
     */
    pending: boolean;
    /**
     * When the playlist stopped being readable; its last songs are kept
     * @type {Date}
     * @memberof ImportedSetDto
     */
    staleSince?: Date;
}


/**
 * @export
 */
export const ImportedSetDtoTypeEnum = {
    Decade: 'DECADE',
    Genre: 'GENRE',
    Fame: 'FAME',
    Chart: 'CHART',
    Special: 'SPECIAL',
    Artist: 'ARTIST',
    Imported: 'IMPORTED'
} as const;
export type ImportedSetDtoTypeEnum = typeof ImportedSetDtoTypeEnum[keyof typeof ImportedSetDtoTypeEnum];

/**
 * @export
 */
export const ImportedSetDtoSourceEnum = {
    Deezer: 'DEEZER',
    Spotify: 'SPOTIFY',
    AppleMusic: 'APPLE_MUSIC'
} as const;
export type ImportedSetDtoSourceEnum = typeof ImportedSetDtoSourceEnum[keyof typeof ImportedSetDtoSourceEnum];


/**
 * Check if a given object implements the ImportedSetDto interface.
 */
export function instanceOfImportedSetDto(value: object): value is ImportedSetDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('trackCount' in value) || value['trackCount'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function ImportedSetDtoFromJSON(json: any): ImportedSetDto {
    return ImportedSetDtoFromJSONTyped(json, false);
}

export function ImportedSetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportedSetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': json['name'],
        'slug': json['slug'],
        'trackCount': json['trackCount'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'source': json['source'],
        'externalUrl': json['externalUrl'],
        'pending': json['pending'],
        'staleSince': json['staleSince'] == null ? undefined : (new Date(json['staleSince'])),
    };
}

export function ImportedSetDtoToJSON(json: any): ImportedSetDto {
    return ImportedSetDtoToJSONTyped(json, false);
}

export function ImportedSetDtoToJSONTyped(value?: ImportedSetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
        'slug': value['slug'],
        'trackCount': value['trackCount'],
        'imageUrl': value['imageUrl'],
        'source': value['source'],
        'externalUrl': value['externalUrl'],
        'pending': value['pending'],
        'staleSince': value['staleSince'] == null ? value['staleSince'] : value['staleSince'].toISOString(),
    };
}

