/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StreakStatusDto } from './StreakStatusDto';
import {
    StreakStatusDtoFromJSON,
    StreakStatusDtoFromJSONTyped,
    StreakStatusDtoToJSON,
    StreakStatusDtoToJSONTyped,
} from './StreakStatusDto';

/**
 * 
 * @export
 * @interface MeStatusDto
 */
export interface MeStatusDto {
    /**
     * Its playedToday means won today: the streak counts wins
     * @type {StreakStatusDto}
     * @memberof MeStatusDto
     */
    streak: StreakStatusDto;
    /**
     * Whether today's daily was finished, won or lost
     * @type {boolean}
     * @memberof MeStatusDto
     */
    dailyPlayedToday: boolean;
    /**
     * Best speed run score, 0 if none
     * @type {number}
     * @memberof MeStatusDto
     */
    speedRunBest: number;
}

/**
 * Check if a given object implements the MeStatusDto interface.
 */
export function instanceOfMeStatusDto(value: object): value is MeStatusDto {
    if (!('streak' in value) || value['streak'] === undefined) return false;
    if (!('dailyPlayedToday' in value) || value['dailyPlayedToday'] === undefined) return false;
    if (!('speedRunBest' in value) || value['speedRunBest'] === undefined) return false;
    return true;
}

export function MeStatusDtoFromJSON(json: any): MeStatusDto {
    return MeStatusDtoFromJSONTyped(json, false);
}

export function MeStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'streak': StreakStatusDtoFromJSON(json['streak']),
        'dailyPlayedToday': json['dailyPlayedToday'],
        'speedRunBest': json['speedRunBest'],
    };
}

export function MeStatusDtoToJSON(json: any): MeStatusDto {
    return MeStatusDtoToJSONTyped(json, false);
}

export function MeStatusDtoToJSONTyped(value?: MeStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'streak': StreakStatusDtoToJSON(value['streak']),
        'dailyPlayedToday': value['dailyPlayedToday'],
        'speedRunBest': value['speedRunBest'],
    };
}

