/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistItemDto } from './PlaylistItemDto';
import {
    PlaylistItemDtoFromJSON,
    PlaylistItemDtoFromJSONTyped,
    PlaylistItemDtoToJSON,
    PlaylistItemDtoToJSONTyped,
} from './PlaylistItemDto';

/**
 * 
 * @export
 * @interface MyPlaylistsDto
 */
export interface MyPlaylistsDto {
    /**
     * 
     * @type {Array<PlaylistItemDto>}
     * @memberof MyPlaylistsDto
     */
    items: Array<PlaylistItemDto>;
    /**
     * Spotify could not be read this time; imports are still listed
     * @type {boolean}
     * @memberof MyPlaylistsDto
     */
    spotifyUnavailable: boolean;
}

/**
 * Check if a given object implements the MyPlaylistsDto interface.
 */
export function instanceOfMyPlaylistsDto(value: object): value is MyPlaylistsDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('spotifyUnavailable' in value) || value['spotifyUnavailable'] === undefined) return false;
    return true;
}

export function MyPlaylistsDtoFromJSON(json: any): MyPlaylistsDto {
    return MyPlaylistsDtoFromJSONTyped(json, false);
}

export function MyPlaylistsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyPlaylistsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PlaylistItemDtoFromJSON)),
        'spotifyUnavailable': json['spotifyUnavailable'],
    };
}

export function MyPlaylistsDtoToJSON(json: any): MyPlaylistsDto {
    return MyPlaylistsDtoToJSONTyped(json, false);
}

export function MyPlaylistsDtoToJSONTyped(value?: MyPlaylistsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PlaylistItemDtoToJSON)),
        'spotifyUnavailable': value['spotifyUnavailable'],
    };
}

