/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenRoomDto } from './OpenRoomDto';
import {
    OpenRoomDtoFromJSON,
    OpenRoomDtoFromJSONTyped,
    OpenRoomDtoToJSON,
    OpenRoomDtoToJSONTyped,
} from './OpenRoomDto';

/**
 * 
 * @export
 * @interface OpenRoomsDto
 */
export interface OpenRoomsDto {
    /**
     * 
     * @type {Array<OpenRoomDto>}
     * @memberof OpenRoomsDto
     */
    rooms: Array<OpenRoomDto>;
}

/**
 * Check if a given object implements the OpenRoomsDto interface.
 */
export function instanceOfOpenRoomsDto(value: object): value is OpenRoomsDto {
    if (!('rooms' in value) || value['rooms'] === undefined) return false;
    return true;
}

export function OpenRoomsDtoFromJSON(json: any): OpenRoomsDto {
    return OpenRoomsDtoFromJSONTyped(json, false);
}

export function OpenRoomsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenRoomsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rooms': ((json['rooms'] as Array<any>).map(OpenRoomDtoFromJSON)),
    };
}

export function OpenRoomsDtoToJSON(json: any): OpenRoomsDto {
    return OpenRoomsDtoToJSONTyped(json, false);
}

export function OpenRoomsDtoToJSONTyped(value?: OpenRoomsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rooms': ((value['rooms'] as Array<any>).map(OpenRoomDtoToJSON)),
    };
}

