/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenRoomDto
 */
export interface OpenRoomDto {
    /**
     * Room id, to join by
     * @type {string}
     * @memberof OpenRoomDto
     */
    id: string;
    /**
     * The room`s name
     * @type {string}
     * @memberof OpenRoomDto
     */
    name: string;
    /**
     * How many players are in it right now
     * @type {number}
     * @memberof OpenRoomDto
     */
    playerCount: number;
    /**
     * Rounds the host chose
     * @type {number}
     * @memberof OpenRoomDto
     */
    roundCount: number;
    /**
     * Whether it draws on the curated pool or on linked libraries
     * @type {string}
     * @memberof OpenRoomDto
     */
    trackSource: OpenRoomDtoTrackSourceEnum;
}


/**
 * @export
 */
export const OpenRoomDtoTrackSourceEnum = {
    Pool: 'POOL',
    Libraries: 'LIBRARIES'
} as const;
export type OpenRoomDtoTrackSourceEnum = typeof OpenRoomDtoTrackSourceEnum[keyof typeof OpenRoomDtoTrackSourceEnum];


/**
 * Check if a given object implements the OpenRoomDto interface.
 */
export function instanceOfOpenRoomDto(value: object): value is OpenRoomDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('playerCount' in value) || value['playerCount'] === undefined) return false;
    if (!('roundCount' in value) || value['roundCount'] === undefined) return false;
    if (!('trackSource' in value) || value['trackSource'] === undefined) return false;
    return true;
}

export function OpenRoomDtoFromJSON(json: any): OpenRoomDto {
    return OpenRoomDtoFromJSONTyped(json, false);
}

export function OpenRoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenRoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'playerCount': json['playerCount'],
        'roundCount': json['roundCount'],
        'trackSource': json['trackSource'],
    };
}

export function OpenRoomDtoToJSON(json: any): OpenRoomDto {
    return OpenRoomDtoToJSONTyped(json, false);
}

export function OpenRoomDtoToJSONTyped(value?: OpenRoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'playerCount': value['playerCount'],
        'roundCount': value['roundCount'],
        'trackSource': value['trackSource'],
    };
}

