/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistItemKind } from './PlaylistItemKind';
import {
    PlaylistItemKindFromJSON,
    PlaylistItemKindFromJSONTyped,
    PlaylistItemKindToJSON,
    PlaylistItemKindToJSONTyped,
} from './PlaylistItemKind';

/**
 * 
 * @export
 * @interface PlaylistItemDto
 */
export interface PlaylistItemDto {
    /**
     * 
     * @type {PlaylistItemKind}
     * @memberof PlaylistItemDto
     */
    kind: PlaylistItemKind;
    /**
     * The Spotify playlist id, or the set id of an import
     * @type {string}
     * @memberof PlaylistItemDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PlaylistItemDto
     */
    trackCount: number;
    /**
     * The playlist on its own service
     * @type {string}
     * @memberof PlaylistItemDto
     */
    externalUrl: string;
    /**
     * The Spotify owner's name
     * @type {string}
     * @memberof PlaylistItemDto
     */
    owner?: string;
    /**
     * Imports: the set page
     * @type {string}
     * @memberof PlaylistItemDto
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemDto
     */
    source?: PlaylistItemDtoSourceEnum;
    /**
     * Imports: songs not read yet
     * @type {boolean}
     * @memberof PlaylistItemDto
     */
    pending?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PlaylistItemDto
     */
    staleSince?: Date;
}


/**
 * @export
 */
export const PlaylistItemDtoSourceEnum = {
    Deezer: 'DEEZER',
    Spotify: 'SPOTIFY',
    AppleMusic: 'APPLE_MUSIC'
} as const;
export type PlaylistItemDtoSourceEnum = typeof PlaylistItemDtoSourceEnum[keyof typeof PlaylistItemDtoSourceEnum];


/**
 * Check if a given object implements the PlaylistItemDto interface.
 */
export function instanceOfPlaylistItemDto(value: object): value is PlaylistItemDto {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('trackCount' in value) || value['trackCount'] === undefined) return false;
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    return true;
}

export function PlaylistItemDtoFromJSON(json: any): PlaylistItemDto {
    return PlaylistItemDtoFromJSONTyped(json, false);
}

export function PlaylistItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': PlaylistItemKindFromJSON(json['kind']),
        'id': json['id'],
        'name': json['name'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'trackCount': json['trackCount'],
        'externalUrl': json['externalUrl'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'source': json['source'] == null ? undefined : json['source'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'staleSince': json['staleSince'] == null ? undefined : (new Date(json['staleSince'])),
    };
}

export function PlaylistItemDtoToJSON(json: any): PlaylistItemDto {
    return PlaylistItemDtoToJSONTyped(json, false);
}

export function PlaylistItemDtoToJSONTyped(value?: PlaylistItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': PlaylistItemKindToJSON(value['kind']),
        'id': value['id'],
        'name': value['name'],
        'imageUrl': value['imageUrl'],
        'trackCount': value['trackCount'],
        'externalUrl': value['externalUrl'],
        'owner': value['owner'],
        'slug': value['slug'],
        'source': value['source'],
        'pending': value['pending'],
        'staleSince': value['staleSince'] == null ? value['staleSince'] : value['staleSince'].toISOString(),
    };
}

