/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestEmailChangeControllerDto
 */
export interface RequestEmailChangeControllerDto {
    /**
     * The password of the signed in account
     * @type {string}
     * @memberof RequestEmailChangeControllerDto
     */
    currentPassword: string;
    /**
     * The address to move the account to
     * @type {string}
     * @memberof RequestEmailChangeControllerDto
     */
    newEmail: string;
}

/**
 * Check if a given object implements the RequestEmailChangeControllerDto interface.
 */
export function instanceOfRequestEmailChangeControllerDto(value: object): value is RequestEmailChangeControllerDto {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newEmail' in value) || value['newEmail'] === undefined) return false;
    return true;
}

export function RequestEmailChangeControllerDtoFromJSON(json: any): RequestEmailChangeControllerDto {
    return RequestEmailChangeControllerDtoFromJSONTyped(json, false);
}

export function RequestEmailChangeControllerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestEmailChangeControllerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newEmail': json['newEmail'],
    };
}

export function RequestEmailChangeControllerDtoToJSON(json: any): RequestEmailChangeControllerDto {
    return RequestEmailChangeControllerDtoToJSONTyped(json, false);
}

export function RequestEmailChangeControllerDtoToJSONTyped(value?: RequestEmailChangeControllerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newEmail': value['newEmail'],
    };
}

