/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackGroupDto } from './TrackGroupDto';
import {
    TrackGroupDtoFromJSON,
    TrackGroupDtoFromJSONTyped,
    TrackGroupDtoToJSON,
    TrackGroupDtoToJSONTyped,
} from './TrackGroupDto';

/**
 * 
 * @export
 * @interface TrackGroupCatalogDto
 */
export interface TrackGroupCatalogDto {
    /**
     * 
     * @type {Array<TrackGroupDto>}
     * @memberof TrackGroupCatalogDto
     */
    artist: Array<TrackGroupDto>;
    /**
     * 
     * @type {Array<TrackGroupDto>}
     * @memberof TrackGroupCatalogDto
     */
    decade: Array<TrackGroupDto>;
    /**
     * 
     * @type {Array<TrackGroupDto>}
     * @memberof TrackGroupCatalogDto
     */
    genre: Array<TrackGroupDto>;
    /**
     * 
     * @type {Array<TrackGroupDto>}
     * @memberof TrackGroupCatalogDto
     */
    chart: Array<TrackGroupDto>;
    /**
     * Empty for everyone the special sets were not made for
     * @type {Array<TrackGroupDto>}
     * @memberof TrackGroupCatalogDto
     */
    special: Array<TrackGroupDto>;
}

/**
 * Check if a given object implements the TrackGroupCatalogDto interface.
 */
export function instanceOfTrackGroupCatalogDto(value: object): value is TrackGroupCatalogDto {
    if (!('artist' in value) || value['artist'] === undefined) return false;
    if (!('decade' in value) || value['decade'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('chart' in value) || value['chart'] === undefined) return false;
    if (!('special' in value) || value['special'] === undefined) return false;
    return true;
}

export function TrackGroupCatalogDtoFromJSON(json: any): TrackGroupCatalogDto {
    return TrackGroupCatalogDtoFromJSONTyped(json, false);
}

export function TrackGroupCatalogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackGroupCatalogDto {
    if (json == null) {
        return json;
    }
    return {
        
        'artist': ((json['artist'] as Array<any>).map(TrackGroupDtoFromJSON)),
        'decade': ((json['decade'] as Array<any>).map(TrackGroupDtoFromJSON)),
        'genre': ((json['genre'] as Array<any>).map(TrackGroupDtoFromJSON)),
        'chart': ((json['chart'] as Array<any>).map(TrackGroupDtoFromJSON)),
        'special': ((json['special'] as Array<any>).map(TrackGroupDtoFromJSON)),
    };
}

export function TrackGroupCatalogDtoToJSON(json: any): TrackGroupCatalogDto {
    return TrackGroupCatalogDtoToJSONTyped(json, false);
}

export function TrackGroupCatalogDtoToJSONTyped(value?: TrackGroupCatalogDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artist': ((value['artist'] as Array<any>).map(TrackGroupDtoToJSON)),
        'decade': ((value['decade'] as Array<any>).map(TrackGroupDtoToJSON)),
        'genre': ((value['genre'] as Array<any>).map(TrackGroupDtoToJSON)),
        'chart': ((value['chart'] as Array<any>).map(TrackGroupDtoToJSON)),
        'special': ((value['special'] as Array<any>).map(TrackGroupDtoToJSON)),
    };
}

