/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateArtistRequestsDto
 */
export interface UpdateArtistRequestsDto {
    /**
     * The grouping key, as the requests list returns it
     * @type {string}
     * @memberof UpdateArtistRequestsDto
     */
    key: string;
    /**
     * Resolved once the set exists, or reopened
     * @type {boolean}
     * @memberof UpdateArtistRequestsDto
     */
    resolved: boolean;
}

/**
 * Check if a given object implements the UpdateArtistRequestsDto interface.
 */
export function instanceOfUpdateArtistRequestsDto(value: object): value is UpdateArtistRequestsDto {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('resolved' in value) || value['resolved'] === undefined) return false;
    return true;
}

export function UpdateArtistRequestsDtoFromJSON(json: any): UpdateArtistRequestsDto {
    return UpdateArtistRequestsDtoFromJSONTyped(json, false);
}

export function UpdateArtistRequestsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateArtistRequestsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'resolved': json['resolved'],
    };
}

export function UpdateArtistRequestsDtoToJSON(json: any): UpdateArtistRequestsDto {
    return UpdateArtistRequestsDtoToJSONTyped(json, false);
}

export function UpdateArtistRequestsDtoToJSONTyped(value?: UpdateArtistRequestsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'resolved': value['resolved'],
    };
}

