/* tslint:disable */
/* eslint-disable */
/**
 * Sopranino API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRoomSettingsControllerDto
 */
export interface UpdateRoomSettingsControllerDto {
    /**
     * What the room is called, in the lobby and to its players
     * @type {string}
     * @memberof UpdateRoomSettingsControllerDto
     */
    name?: string;
    /**
     * Whether the room is listed for anyone to find. Off makes it reachable only by its invite code.
     * @type {boolean}
     * @memberof UpdateRoomSettingsControllerDto
     */
    findable?: boolean;
    /**
     * Number of rounds for the game
     * @type {number}
     * @memberof UpdateRoomSettingsControllerDto
     */
    roundCount?: UpdateRoomSettingsControllerDtoRoundCountEnum;
}


/**
 * @export
 */
export const UpdateRoomSettingsControllerDtoRoundCountEnum = {
    NUMBER_3: 3,
    NUMBER_5: 5,
    NUMBER_10: 10
} as const;
export type UpdateRoomSettingsControllerDtoRoundCountEnum = typeof UpdateRoomSettingsControllerDtoRoundCountEnum[keyof typeof UpdateRoomSettingsControllerDtoRoundCountEnum];


/**
 * Check if a given object implements the UpdateRoomSettingsControllerDto interface.
 */
export function instanceOfUpdateRoomSettingsControllerDto(value: object): value is UpdateRoomSettingsControllerDto {
    return true;
}

export function UpdateRoomSettingsControllerDtoFromJSON(json: any): UpdateRoomSettingsControllerDto {
    return UpdateRoomSettingsControllerDtoFromJSONTyped(json, false);
}

export function UpdateRoomSettingsControllerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoomSettingsControllerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'findable': json['findable'] == null ? undefined : json['findable'],
        'roundCount': json['roundCount'] == null ? undefined : json['roundCount'],
    };
}

export function UpdateRoomSettingsControllerDtoToJSON(json: any): UpdateRoomSettingsControllerDto {
    return UpdateRoomSettingsControllerDtoToJSONTyped(json, false);
}

export function UpdateRoomSettingsControllerDtoToJSONTyped(value?: UpdateRoomSettingsControllerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'findable': value['findable'],
        'roundCount': value['roundCount'],
    };
}

