-- AlterEnum
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'YOUTUBE';
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'AMAZON_MUSIC';
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'TIDAL';
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'SOUNDCLOUD';
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'PANDORA';
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'NAPSTER';
ALTER TYPE "PlaylistSource" ADD VALUE IF NOT EXISTS 'OTHER';
